version: '3.6'

services:
  main-app:
    image: quiz-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["/bin/sh", "-c", "bun run start"]
    depends_on:
      - db  

  worker:
    image: quiz-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    command: ["/bin/sh", "-c", "bun run start worker"]
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
